//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhiThanh.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhiThanh.Resources.ValidationMessage", typeof(ValidationMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exists.
        /// </summary>
        public static string ERR_001_USER_NOT_EXISTS {
            get {
                return ResourceManager.GetString("ERR_001_USER_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not correct.
        /// </summary>
        public static string ERR_002_PASSWORD_NOT_CORRECT {
            get {
                return ResourceManager.GetString("ERR_002_PASSWORD_NOT_CORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName already exists.
        /// </summary>
        public static string ERR_003_USER_ALREADY_EXSITS {
            get {
                return ResourceManager.GetString("ERR_003_USER_ALREADY_EXSITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data does not exists.
        /// </summary>
        public static string ERR_004_DATA_NOT_EXISTS {
            get {
                return ResourceManager.GetString("ERR_004_DATA_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted data does not exists.
        /// </summary>
        public static string ERR_005_DATA_DELETE_NOT_EXISTS {
            get {
                return ResourceManager.GetString("ERR_005_DATA_DELETE_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your account to continue.
        /// </summary>
        public static string ERR_006_USER_NOT_VERIFY {
            get {
                return ResourceManager.GetString("ERR_006_USER_NOT_VERIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category alreaddy exists.
        /// </summary>
        public static string ERR_007_CATEGORY_DUPLICATE {
            get {
                return ResourceManager.GetString("ERR_007_CATEGORY_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game not exists.
        /// </summary>
        public static string ERR_008_GAME_NOT_EXISTS {
            get {
                return ResourceManager.GetString("ERR_008_GAME_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game already published.
        /// </summary>
        public static string ERR_009_GAME_ALREADY_PUBLISHED {
            get {
                return ResourceManager.GetString("ERR_009_GAME_ALREADY_PUBLISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not exists.
        /// </summary>
        public static string ERR_010_ITEM_NOT_EXISTS {
            get {
                return ResourceManager.GetString("ERR_010_ITEM_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url not valid.
        /// </summary>
        public static string ERR_011_URL_NOT_VALID {
            get {
                return ResourceManager.GetString("ERR_011_URL_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot upload files.
        /// </summary>
        public static string ERR_012_UPLOAD_FILE_ERROR {
            get {
                return ResourceManager.GetString("ERR_012_UPLOAD_FILE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions not support.
        /// </summary>
        public static string ERR_013_EXTENSIONS_NOT_SUPPORT {
            get {
                return ResourceManager.GetString("ERR_013_EXTENSIONS_NOT_SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player not exists.
        /// </summary>
        public static string ERR_014_PLAYER_NOT_EXISTS {
            get {
                return ResourceManager.GetString("ERR_014_PLAYER_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of ticket.
        /// </summary>
        public static string ERR_015_OUT_OF_TICKET {
            get {
                return ResourceManager.GetString("ERR_015_OUT_OF_TICKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create or update template..
        /// </summary>
        public static string ERR_016_CANNOT_CREATE_OR_UPDATE_TEMPLATE {
            get {
                return ResourceManager.GetString("ERR_016_CANNOT_CREATE_OR_UPDATE_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game is not valid to be published.
        /// </summary>
        public static string ERR_017_GAME_NOT_VALID_TO_PUBLISH {
            get {
                return ResourceManager.GetString("ERR_017_GAME_NOT_VALID_TO_PUBLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status not valid.
        /// </summary>
        public static string ERR_018_STATUS_NOT_VALID {
            get {
                return ResourceManager.GetString("ERR_018_STATUS_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot choose current lottery for cross rewards.
        /// </summary>
        public static string ERR_019_LOTTERY_REWARD_LOOPED {
            get {
                return ResourceManager.GetString("ERR_019_LOTTERY_REWARD_LOOPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceId has been used.
        /// </summary>
        public static string ERR_020_DEVICE_ALREADY_BIND {
            get {
                return ResourceManager.GetString("ERR_020_DEVICE_ALREADY_BIND", resourceCulture);
            }
        }
    }
}
